### ISSUE TITLE
Redmine crashes after plugin install on redmine 2.2.2

### ISSUE THREAD

**Issue by EchoRider999** [tleish/redmine_revision_branches#15]
Hi,
After install your plugin, redmine crashes.
This is an old version but compatible with your plugin.
Can you please tell me why I have this error ?
Thank you
Regards.

Here is the information :

> Environment:
>   Redmine version                          2.2.2.stable
>   Ruby version                             1.8.7 (x86_64-linux)
>   Rails version                            3.2.11
>   Environment                              production
>   Database adapter                         MySQL
> Redmine plugins:
>   clipboard_image_paste                    1.6a
>   my_projects                              1.0
>   redmine_code_review                      0.6.1
>   redmine_graphs                           0.1.0

Here is redmine logs :

```
[ 2016-07-29 14:44:50.1249 13522/7fd6de5b3700 App/Implementation.cpp:303 ]: Could not spawn process for application /var/www/redmine: An error occured while starting up the preloader.
  Error ID: 8c1e7ab6
  Error details saved to: /tmp/passenger-error-ixV5F8.html
  Message from application: /var/www/redmine/plugins/redmine_revision_branches/init.rb:11: odd number list for Hash
...display_under_single_revision: true, display_under_associate...
                              ^
/var/www/redmine/plugins/redmine_revision_branches/init.rb:11: syntax error, unexpected ':', expecting '}'
...display_under_single_revision: true, display_under_associate...
                              ^
/var/www/redmine/plugins/redmine_revision_branches/init.rb:11: Can't assign to true
...y_under_single_revision: true, display_under_associated_revi...
                              ^
/var/www/redmine/plugins/redmine_revision_branches/init.rb:11: syntax error, unexpected ':', expecting '='
...ay_under_associated_revisions: false }, :partial => 'redmine...
                              ^ (SyntaxError)
  /usr/lib/ruby/gems/1.8/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `require'
  /usr/lib/ruby/gems/1.8/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `require'
  /usr/lib/ruby/gems/1.8/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:236:in `load_dependency'
  /usr/lib/ruby/gems/1.8/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `require'
  /var/www/redmine/lib/redmine/plugin.rb:130:in `load'
  /var/www/redmine/lib/redmine/plugin.rb:121:in `each'
  /var/www/redmine/lib/redmine/plugin.rb:121:in `load'
  /var/www/redmine/config/initializers/30-redmine.rb:12
  /usr/lib/ruby/gems/1.8/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:245:in `load'
  /usr/lib/ruby/gems/1.8/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:245:in `load'
  /usr/lib/ruby/gems/1.8/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:236:in `load_dependency'
  /usr/lib/ruby/gems/1.8/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:245:in `load'
  /usr/lib/ruby/gems/1.8/gems/railties-3.2.11/lib/rails/engine.rb:588
  /usr/lib/ruby/gems/1.8/gems/railties-3.2.11/lib/rails/engine.rb:587:in `each'
  /usr/lib/ruby/gems/1.8/gems/railties-3.2.11/lib/rails/engine.rb:587
  /usr/lib/ruby/gems/1.8/gems/railties-3.2.11/lib/rails/initializable.rb:30:in `instance_exec'
  /usr/lib/ruby/gems/1.8/gems/railties-3.2.11/lib/rails/initializable.rb:30:in `run'
  /usr/lib/ruby/gems/1.8/gems/railties-3.2.11/lib/rails/initializable.rb:55:in `run_initializers'
  /usr/lib/ruby/gems/1.8/gems/railties-3.2.11/lib/rails/initializable.rb:54:in `each'
  /usr/lib/ruby/gems/1.8/gems/railties-3.2.11/lib/rails/initializable.rb:54:in `run_initializers'
  /usr/lib/ruby/gems/1.8/gems/railties-3.2.11/lib/rails/application.rb:136:in `initialize!'
  /usr/lib/ruby/gems/1.8/gems/railties-3.2.11/lib/rails/railtie/configurable.rb:30:in `send'
  /usr/lib/ruby/gems/1.8/gems/railties-3.2.11/lib/rails/railtie/configurable.rb:30:in `method_missing'
  /var/www/redmine/config/environment.rb:15
  config.ru:3:in `require'
  config.ru:3
  /usr/lib/ruby/gems/1.8/gems/rack-1.4.7/lib/rack/builder.rb:51:in `instance_eval'
  /usr/lib/ruby/gems/1.8/gems/rack-1.4.7/lib/rack/builder.rb:51:in `initialize'
  config.ru:1:in `new'
  config.ru:1


[ 2016-07-29 14:44:50.1325 13522/7fd6d8be6700 age/Cor/Req/CheckoutSession.cpp:252 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is 8c1e7ab6. Please see earlier logs for details about the error.


```

**Comment by tleish** [comment]
The plugin requires Ruby 1.9+, where your environment is running Ruby 1.8.

**Comment by EchoRider999** [comment]
Not see this prerequisite, but OK, this is it, Thanks.
Regards
